
export BASE = helm
export CHART = cluster-autoscaler
export NAMESPACE = kube-system
export REPO = autoscaler
export URL = https://kubernetes.github.io/autoscaler
export VERSION = 9.21.0

include ../Makefile.kustomize

seal:
_PHONY: seal
