
export BASE = helm
export CHART = grafana
export NAMESPACE = monitoring
export REPO = grafana
export URL = https://grafana.github.io/helm-charts
export VERSION = 6.51.1

include ../Makefile.kustomize

seal:
_PHONY: seal
