
export BASE = helm
export CHART = external-dns
export NAMESPACE = kube-system
export REPO = bitnami
export URL = https://charts.bitnami.com/bitnami
export VERSION = 6.12.1

include ../Makefile.kustomize

seal:
_PHONY: seal
