
export BASE = helm
export CHART = kube-state-metrics
export NAMESPACE = kube-system
export REPO = kube-state-metrics
export URL = https://kubernetes.github.io/kube-state-metrics
export VERSION = 2.13.3

include ../Makefile.kustomize

seal:
_PHONY: seal
