
export BASE = helm
export CHART = aws-vpc-cni
export NAMESPACE = kube-system
export REPO = eks
export URL = https://aws.github.io/eks-charts
export VERSION = 1.2.6

include ../Makefile.kustomize

seal:
_PHONY: seal
