
export BASE = helm
export CHART = promtail
export NAMESPACE = monitoring
export REPO = grafana
export URL = https://grafana.github.io/helm-charts
export VERSION = 6.9.0

include ../Makefile.kustomize

seal:
_PHONY: seal
