
export BASE = helm
export CHART = aws-ebs-csi-driver
export NAMESPACE = kube-system
export REPO = aws-ebs-csi-driver
export URL = https://kubernetes-sigs.github.io/aws-ebs-csi-driver
export VERSION = 2.16.0

include ../Makefile.kustomize

seal:
_PHONY: seal
