export BASE = helm
export CHART = cert-manager
export NAMESPACE = cert-manager
export REPO = jetstack
export URL = https://charts.jetstack.io
export VERSION = v1.11.0

include ../Makefile.kustomize

seal:
_PHONY: seal
