
export BASE = helm
export CHART = nginx-ingress
export NAMESPACE = ingress-nginx
export REPO = nginx-stable
export URL = https://helm.nginx.com/stable
export VERSION = 0.16.2

include ../Makefile.kustomize

seal:
_PHONY: seal
