
export BASE = helm
export CHART = prometheus
export NAMESPACE = monitoring
export REPO = prometheus
export URL = https://prometheus-community.github.io/helm-charts
export VERSION = 19.7.2

include ../Makefile.kustomize

seal:
_PHONY: seal
