
export BASE = helm
export CHART = alertmanager
export NAMESPACE = monitoring
export REPO = prometheus-community
export URL = https://prometheus-community.github.io/helm-charts
export VERSION = 0.26.0

include ../Makefile.kustomize

seal:
_PHONY: seal
