
export BASE = helm
export CHART = aws-load-balancer-controller
export NAMESPACE = kube-system
export REPO = eks
export URL = https://aws.github.io/eks-charts
export VERSION = 1.4.6

include ../Makefile.kustomize

seal:
_PHONY: seal
