
export BASE = helm
export CHART = coredns
export NAMESPACE = kube-system
export REPO = coredns
export URL = https://coredns.github.io/helm
export VERSION = 1.19.7

include ../Makefile.kustomize

seal:
_PHONY: seal

 