
export BASE = helm
export CHART = loki
export NAMESPACE = monitoring
export REPO = grafana
export URL = https://grafana.github.io/helm-charts
export VERSION = 4.7.0

include ../Makefile.kustomize

seal:
_PHONY: seal
