
export BASE = helm
export CHART = aws-efs-csi-driver
export NAMESPACE = kube-system
export REPO = aws-efs-csi-driver
export URL = https://kubernetes-sigs.github.io/aws-efs-csi-driver/
export VERSION = 2.3.8

include ../Makefile.kustomize

seal:
_PHONY: seal
