
export BASE = helm
export CHART = nri-bundle
export NAMESPACE = newrelic
export REPO = newrelic
export URL = https://helm-charts.newrelic.com
export VERSION = 5.0.2

include ../Makefile.kustomize

seal:
_PHONY: seal
