
export BASE = helm
export CHART = metrics-server
export NAMESPACE = kube-system
export REPO = metrics-server
export URL = https://kubernetes-sigs.github.io/metrics-server/
export VERSION = 3.8.3

include ../Makefile.kustomize

seal:
_PHONY: seal
